-- Dedicated webhook signing keys (authvital-broker key-exposure reduction).
-- Additive only: existing rows default to TOKEN purpose, preserving current
-- behavior for JWT signing. A WEBHOOK-purpose key is generated by the core
-- KeyManagerService on next startup.

-- CreateEnum
CREATE TYPE "SigningKeyPurpose" AS ENUM ('TOKEN', 'WEBHOOK');

-- AlterTable
ALTER TABLE "signing_keys"
  ADD COLUMN "purpose" "SigningKeyPurpose" NOT NULL DEFAULT 'TOKEN';

-- CreateIndex
CREATE INDEX "signing_keys_status_purpose_idx" ON "signing_keys"("status", "purpose");
